vrrp_script chk_nginx {
    script "/etc/keepalived/check_nginx.sh"
    interval 2
    weight -20
}

vrrp_instance VI_1 {
    state MASTER
    interface ens5
    virtual_router_id 51
    priority 100
    advert_int 1
    unicast_src_ip 172.26.0.95
    unicast_peer {
        172.26.15.239
    }

    authentication {
        auth_type PASS
        auth_pass 1234
    }

    virtual_ipaddress {
        172.26.0.100
    }

    track_script {
        chk_nginx
    }

    nopreempt
}

